name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: true
      SLACK_TITLE: Pull Request Status
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: CI
      SLACK_ICON: "https://img.icons8.com/ios/50/000000/book-philosophy.png"
    steps:
      - uses: actions/checkout@v1

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command

      - uses: rtCamp/action-slack-notify@v2.0.0
        name: Slack Success Notification
        if: success()
        env:
          SLACK_COLOR: '#1e824c'
          SLACK_MESSAGE: Success 🚀! <https://github.com/${{github.repository}}/pull/${{github.event.number}}| Link to PR ${{github.event.number}}>

      - uses: rtCamp/action-slack-notify@v2.0.0
        name: Slack Failure Notification
        if: failure()
        env:
          SLACK_COLOR: '#f83535'
          SLACK_MESSAGE: Build Failed 😿 <https://github.com/${{github.repository}}/pull/${{github.event.number}}| Link to PR ${{github.event.number}}>

      - uses: rtCamp/action-slack-notify@v2.0.0
        name: Slack Stopped Notification
        if: cancelled()
        env:
          SLACK_COLOR: '#adadad'
          SLACK_MESSAGE: Build Stopped ✋🏻 <https://github.com/${{github.repository}}/pull/${{github.event.number}}| Link to PR ${{github.event.number}}>
